-- MySQL Script generated by MySQL Workbench
-- Mon Mar 23 19:45:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema techwizard
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `techwizard` ;

-- -----------------------------------------------------
-- Schema techwizard
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `techwizard` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `techwizard` ;

-- -----------------------------------------------------
-- Table `techwizard`.`ContactMethods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `techwizard`.`ContactMethods` ;

CREATE TABLE IF NOT EXISTS `techwizard`.`ContactMethods` (
  `ContactMethodID` INT NOT NULL AUTO_INCREMENT,
  `MethodName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ContactMethodID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techwizard`.`Skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `techwizard`.`Skills` ;

CREATE TABLE IF NOT EXISTS `techwizard`.`Skills` (
  `SkillsId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`SkillsId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techwizard`.`WizardSkills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `techwizard`.`WizardSkills` ;

CREATE TABLE IF NOT EXISTS `techwizard`.`WizardSkills` (
  `user_UserID` INT(11) NOT NULL,
  `Skills_SkillsId` INT NOT NULL,
  PRIMARY KEY (`user_UserID`, `Skills_SkillsId`),
  CONSTRAINT `fk_WizardSkills_user1`
    FOREIGN KEY (`user_UserID`)
    REFERENCES `techwizard`.`user` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WizardSkills_Skills1`
    FOREIGN KEY (`Skills_SkillsId`)
    REFERENCES `techwizard`.`Skills` (`SkillsId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_WizardSkills_Skills1_idx` ON `techwizard`.`WizardSkills` (`Skills_SkillsId` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `techwizard`.`WorkRequests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `techwizard`.`WorkRequests` ;

CREATE TABLE IF NOT EXISTS `techwizard`.`WorkRequests` (
  `RequestId` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(500) NOT NULL,
  `user_UserID` INT(11) NOT NULL,
  `Skills_SkillsId` INT NOT NULL,
  `CreatedDate` DATETIME NOT NULL,
  `AcceptedDate` DATETIME NULL,
  `hoursWorked` INT NULL,
  `CompletedDate` DATETIME NULL,
  `user_WizardID` INT(11) NULL,
  `price_in_cents` INT(10) NULL,
  `title` VARCHAR(45) NOT NULL,
  `ContactMethodID` INT NOT NULL,
  PRIMARY KEY (`RequestId`, `user_UserID`, `Skills_SkillsId`, `ContactMethodID`),
  CONSTRAINT `fk_WorkRequests_user`
    FOREIGN KEY (`user_UserID`)
    REFERENCES `techwizard`.`user` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WorkRequests_Skills1`
    FOREIGN KEY (`Skills_SkillsId`)
    REFERENCES `techwizard`.`Skills` (`SkillsId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WorkRequests_user1`
    FOREIGN KEY (`user_WizardID`)
    REFERENCES `techwizard`.`user` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WorkRequests_ContactMethods1`
    FOREIGN KEY (`ContactMethodID`)
    REFERENCES `techwizard`.`ContactMethods` (`ContactMethodID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_WorkRequests_user_idx` ON `techwizard`.`WorkRequests` (`user_UserID` ASC) VISIBLE;

CREATE INDEX `fk_WorkRequests_Skills1_idx` ON `techwizard`.`WorkRequests` (`Skills_SkillsId` ASC) VISIBLE;

CREATE INDEX `fk_WorkRequests_user1_idx` ON `techwizard`.`WorkRequests` (`user_WizardID` ASC) VISIBLE;

CREATE INDEX `fk_WorkRequests_ContactMethods1_idx` ON `techwizard`.`WorkRequests` (`ContactMethodID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `techwizard`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `techwizard`.`user` ;

CREATE TABLE IF NOT EXISTS `techwizard`.`user` (
  `UserID` INT(11) NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(45) NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `State` VARCHAR(45) NOT NULL,
  `Zip` INT(11) NOT NULL,
  `Phone` VARCHAR(15) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `isWizard` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `UserName_UNIQUE` ON `techwizard`.`user` (`UserName` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `techwizard`.`ContactMethods`
-- -----------------------------------------------------
START TRANSACTION;
USE `techwizard`;
INSERT INTO `techwizard`.`ContactMethods` (`ContactMethodID`, `MethodName`) VALUES (1, 'Text');
INSERT INTO `techwizard`.`ContactMethods` (`ContactMethodID`, `MethodName`) VALUES (2, 'Phone');
INSERT INTO `techwizard`.`ContactMethods` (`ContactMethodID`, `MethodName`) VALUES (3, 'Email');
INSERT INTO `techwizard`.`ContactMethods` (`ContactMethodID`, `MethodName`) VALUES (4, 'In-Person');

COMMIT;


-- -----------------------------------------------------
-- Data for table `techwizard`.`Skills`
-- -----------------------------------------------------
START TRANSACTION;
USE `techwizard`;
INSERT INTO `techwizard`.`Skills` (`SkillsId`, `Name`) VALUES (1, 'Windows');
INSERT INTO `techwizard`.`Skills` (`SkillsId`, `Name`) VALUES (2, 'MacOS');
INSERT INTO `techwizard`.`Skills` (`SkillsId`, `Name`) VALUES (3, 'Android');
INSERT INTO `techwizard`.`Skills` (`SkillsId`, `Name`) VALUES (4, 'iOS');
INSERT INTO `techwizard`.`Skills` (`SkillsId`, `Name`) VALUES (5, 'Linux');
INSERT INTO `techwizard`.`Skills` (`SkillsId`, `Name`) VALUES (6, 'Hardware');

COMMIT;

